In [1]:
import pandas as pd
import numpy as np

In [2]:
toronto = pd.read_csv("../data/Toronto.csv", parse_dates=["Date"], index_col=False)

In [3]:
toronto.iloc[0:31]

,Date,Longitude,Latitude,Elevation,Max Temperature,Min Temperature
0,1979-01-01,-79.375,43.555901,75,7.856,-2.359
1,1979-01-02,-79.375,43.555901,75,-2.738,-6.021
2,1979-01-03,-79.375,43.555901,75,-7.212,-12.742
3,1979-01-04,-79.375,43.555901,75,-8.569,-10.751
4,1979-01-05,-79.375,43.555901,75,-9.133,-13.273
5,1979-01-06,-79.375,43.555901,75,-5.491,-9.825
6,1979-01-07,-79.375,43.555901,75,-5.457,-7.792
7,1979-01-08,-79.375,43.555901,75,-4.451,-9.121
8,1979-01-09,-79.375,43.555901,75,-7.570,-11.125
9,1979-01-10,-79.375,43.555901,75,-7.229,-13.881
10,1979-01-11,-79.375,43.555901,75,-8.210,-13.821
11,1979-01-12,-79.375,43.555901,75,-5.769,-10.719
12,1979-01-13,-79.375,43.555901,75,2.143,-5.681
13,1979-01-14,-79.375,43.555901,75,3.107,-6.764
14,1979-01-15,-79.375,43.555901,75,-6.941,-11.777
15,1979-01-16,-79.375,43.555901,75,-5.889,-9.783
16,1979-01-17,-79.375,43.555901,75,0.352,-8.805
17,1979-01-18,-79.375,43.555901,75,-3.959,-16.686
18,1979-01-19,-79.375,43.555901,75,-7.307,-16.174
19,1979-01-20,-79.375,43.555901,75,1.198,-7.424
20,1979-01-21,-79.375,43.555901,75,-0.112,-3.815
21,1979-01-22,-79.375,43.555901,75,-0.992,-2.944
22,1979-01-23,-79.375,43.555901,75,-0.229,-3.118
23,1979-01-24,-79.375,43.555901,75,2.612,-1.983
24,1979-01-25,-79.375,43.555901,75,2.048,0.808
25,1979-01-26,-79.375,43.555901,75,1.595,0.787
26,1979-01-27,-79.375,43.555901,75,1.565,0.248
27,1979-01-28,-79.375,43.555901,75,1.594,-1.899
28,1979-01-29,-79.375,43.555901,75,-1.738,-3.078
29,1979-01-30,-79.375,43.555901,75,-2.060,-4.491
30,1979-01-31,-79.375,43.555901,75,-4.691,-8.699

In [6]:
toronto.iloc[0:31,[0, 4, 5]]

         Date  Max Temperature  Min Temperature
0  1979-01-01            7.856           -2.359
1  1979-01-02           -2.738           -6.021
2  1979-01-03           -7.212          -12.742
3  1979-01-04           -8.569          -10.751
4  1979-01-05           -9.133          -13.273
5  1979-01-06           -5.491           -9.825
6  1979-01-07           -5.457           -7.792
7  1979-01-08           -4.451           -9.121
8  1979-01-09           -7.570          -11.125
9  1979-01-10           -7.229          -13.881
10 1979-01-11           -8.210          -13.821
11 1979-01-12           -5.769          -10.719
12 1979-01-13            2.143           -5.681
13 1979-01-14            3.107           -6.764
14 1979-01-15           -6.941          -11.777
15 1979-01-16           -5.889           -9.783
16 1979-01-17            0.352           -8.805
17 1979-01-18           -3.959          -16.686
18 1979-01-19           -7.307          -16.174
19 1979-01-20            1.198           -7.424
20 1979-01-21           -0.112           -3.815
21 1979-01-22           -0.992           -2.944
22 1979-01-23           -0.229           -3.118
23 1979-01-24            2.612           -1.983
24 1979-01-25            2.048            0.808
25 1979-01-26            1.595            0.787
26 1979-01-27            1.565            0.248
27 1979-01-28            1.594           -1.899
28 1979-01-29           -1.738           -3.078
29 1979-01-30           -2.060           -4.491
30 1979-01-31           -4.691           -8.699

In [12]:
toronto.loc[toronto['Date'] < '1979-2-1']

,Date,Longitude,Latitude,Elevation,Max Temperature,Min Temperature
0,1979-01-01,-79.375,43.555901,75,7.856,-2.359
1,1979-01-02,-79.375,43.555901,75,-2.738,-6.021
2,1979-01-03,-79.375,43.555901,75,-7.212,-12.742
3,1979-01-04,-79.375,43.555901,75,-8.569,-10.751
4,1979-01-05,-79.375,43.555901,75,-9.133,-13.273
5,1979-01-06,-79.375,43.555901,75,-5.491,-9.825
6,1979-01-07,-79.375,43.555901,75,-5.457,-7.792
7,1979-01-08,-79.375,43.555901,75,-4.451,-9.121
8,1979-01-09,-79.375,43.555901,75,-7.570,-11.125
9,1979-01-10,-79.375,43.555901,75,-7.229,-13.881
10,1979-01-11,-79.375,43.555901,75,-8.210,-13.821
11,1979-01-12,-79.375,43.555901,75,-5.769,-10.719
12,1979-01-13,-79.375,43.555901,75,2.143,-5.681
13,1979-01-14,-79.375,43.555901,75,3.107,-6.764
14,1979-01-15,-79.375,43.555901,75,-6.941,-11.777
15,1979-01-16,-79.375,43.555901,75,-5.889,-9.783
16,1979-01-17,-79.375,43.555901,75,0.352,-8.805
17,1979-01-18,-79.375,43.555901,75,-3.959,-16.686
18,1979-01-19,-79.375,43.555901,75,-7.307,-16.174
19,1979-01-20,-79.375,43.555901,75,1.198,-7.424
20,1979-01-21,-79.375,43.555901,75,-0.112,-3.815
21,1979-01-22,-79.375,43.555901,75,-0.992,-2.944
22,1979-01-23,-79.375,43.555901,75,-0.229,-3.118
23,1979-01-24,-79.375,43.555901,75,2.612,-1.983
24,1979-01-25,-79.375,43.555901,75,2.048,0.808
25,1979-01-26,-79.375,43.555901,75,1.595,0.787
26,1979-01-27,-79.375,43.555901,75,1.565,0.248
27,1979-01-28,-79.375,43.555901,75,1.594,-1.899
28,1979-01-29,-79.375,43.555901,75,-1.738,-3.078
29,1979-01-30,-79.375,43.555901,75,-2.060,-4.491
30,1979-01-31,-79.375,43.555901,75,-4.691,-8.699

In [14]:
toronto.loc[(toronto['Date'] > '1980-1-1') & (toronto['Date'] < '1981-1-1')]

,Date,Longitude,Latitude,Elevation,Max Temperature,Min Temperature
366,1980-01-02,-79.375,43.555901,75,1.237,-1.905
367,1980-01-03,-79.375,43.555901,75,-2.373,-7.739
368,1980-01-04,-79.375,43.555901,75,-3.950,-8.717
369,1980-01-05,-79.375,43.555901,75,-3.606,-6.476
370,1980-01-06,-79.375,43.555901,75,-2.054,-7.426
...,...,...,...,...,...,...
726,1980-12-27,-79.375,43.555901,75,-4.582,-8.505
727,1980-12-28,-79.375,43.555901,75,-1.204,-7.209
728,1980-12-29,-79.375,43.555901,75,-0.513,-1.497
729,1980-12-30,-79.375,43.555901,75,-1.498,-13.730
730,1980-12-31,-79.375,43.555901,75,-8.273,-13.844

In [15]:
toronto.loc[(toronto['Date'] > '1980-1-1') & (toronto['Date'] < '1981-1-1'), "Max Temperature"]

366    1.237
367   -2.373
368   -3.950
369   -3.606
370   -2.054
       ...
726   -4.582
727   -1.204
728   -0.513
729   -1.498
730   -8.273
Name: Max Temperature, Length: 365, dtype: float64